// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUsGQEIqnBSuOBvVyXPiL6hw9iGbCcnQc',
    appId: '1:795469088626:web:bf4e74c39ef57cfe947feb',
    messagingSenderId: '795469088626',
    projectId: 'ferrynavios',
    authDomain: 'ferrynavios.firebaseapp.com',
    storageBucket: 'ferrynavios.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZLeC0GVf_PBd0ZCbE--NEvQbLgb2_fAU',
    appId: '1:795469088626:android:f65b597b7a5ecae3947feb',
    messagingSenderId: '795469088626',
    projectId: 'ferrynavios',
    storageBucket: 'ferrynavios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANRud59jAGTsdSn6gCs1V0smzar9WoqBA',
    appId: '1:795469088626:ios:63e7da19c2afe175947feb',
    messagingSenderId: '795469088626',
    projectId: 'ferrynavios',
    storageBucket: 'ferrynavios.appspot.com',
    iosBundleId: 'com.example.ferrynav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANRud59jAGTsdSn6gCs1V0smzar9WoqBA',
    appId: '1:795469088626:ios:63e7da19c2afe175947feb',
    messagingSenderId: '795469088626',
    projectId: 'ferrynavios',
    storageBucket: 'ferrynavios.appspot.com',
    iosBundleId: 'com.example.ferrynav',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUsGQEIqnBSuOBvVyXPiL6hw9iGbCcnQc',
    appId: '1:795469088626:web:de3da996c40a863f947feb',
    messagingSenderId: '795469088626',
    projectId: 'ferrynavios',
    authDomain: 'ferrynavios.firebaseapp.com',
    storageBucket: 'ferrynavios.appspot.com',
  );
}
